MSG_INVALID_DUTY_DIAPASON = "Invalid value of 'duty1' value. Valid diapason is 0 - 100 (%)"
MSG_INVALID_DUTY_ONE = "Invalid type of 'duty1' value"
MSG_INVALID_FREQ_ONE = "Invalid type of 'freq1' value"
MSG_INVALID_FREQ_DIAPASON = "Invalid value of 'freq1' value. Valid values (Hz) are 1, 2, 5, 10, 20, 50, 100, 200, 500"
MSG_ADDRESS_DONT_EXIST= "Not found"
MSG_NO_ADDRESS = "Please specify 'address' value"
